### ISSUE TITLE
Program for testing Client Library APIs

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#15]
Create command line utility that can exercise ChronoLog client API 

can be used for functional testing immediately and for administrative diagnostics on the running cluster later on

**Comment by fkengun** [comment]
Let's call it ChronoAdmin

**Comment by aparnasasidharan2017** [comment]
Would it be okay to write test cases and use ctest (CLI from cmake) to invoke the tests?

**Comment by ibrodkin** [comment]
I see the ChronoAdmin as a standalone process that links with chronolog client library and will execise client  API commands.
parameters like IP:port for ChronoVisor, client user role, chronicle name , etc will be passed on the command line.

the first priority is to build it as a separate target and be able to invoke it on the command line. Think of it as clientSimulator process.

**Comment by aparnasasidharan2017** [comment]
Completed and closed.
