### ISSUE TITLE
Decouple Configuration Manager and ChronoVisor RPC initialization

### ISSUE THREAD

**Issue by fkengun** [grc-iit/chronolog#17]
Currently, RPC works without major problem with default configurations on both Visor and Client side. But custom configuration settings need to work to allow passing Visor URI (ip+port) from the command line in the CLI tool. In the future, other configurations need to be set on launch as well, such as protocol, thread pool size, and directory with persist data files to recovery from.

**Comment by ibrodkin** [comment]
Configuration object needs to be decoupled from the RPC initialization.  Configuration object reads the configuration file written in JSON and stores the config values as key-value hierarchy in memory.   This is a global object for the process . When the process needs to instantiate the RPCChannels or any other objects with configurable parameters it gets the Configuration Object instance and requests the value for the key .

**Comment by fkengun** [comment]
Merged.
