### ISSUE TITLE
Deserialization likely to fail in Grapher

### ISSUE THREAD

**Issue by fkengun** [grc-iit/chronolog#172]
The current Cereal-based deserialization is likely to fail in Grapher. 

- The Cereal exception message is like `Failed to read 8 bytes from input stream! Read 1`.
- The error does not always happen.
- The same story chunk can be extracted successfully the next time using the same code in potentially another Keeper extraction thread.

**Comment by ibrodkin** [comment]
@fkengun  Please, update this ticket if you can still observe the issue. Please, close the ticket if the issue has been resolved.

**Comment by fkengun** [comment]
resolved in #166
