### ISSUE TITLE
Extend support for intel and Clang compilers

### ISSUE THREAD

**Issue by aparnasasidharan2017** [grc-iit/chronolog#21]
Extend the build system with support for Intel and Clang compilers
Make sure the software stack works with different compilers and compilation flags
Use debuggers from Intel (Inspector) for detecting data races and detecting memory leaks

**Comment by aparnasasidharan2017** [comment]
@fkengun Known issue : When compiled with icpc, ChronoVisor fails with a memory allocation error in ClientRegistryManager, MetadataDirectory and other classes with global scope. I am adding this as a known bug, until we find a place to record known bugs.

**Comment by ibrodkin** [comment]
I think that until our low level dependencies (libfabric, mercury, thallium, etc) are supported on different architectures any effort to build our code with different compilers are a low priority curiosity exercise.  
For example mercury explicitly disables anything but sockets in libfabric instantiation on macOS.

**Comment by fkengun** [comment]
I agree with @ibrodkin that this should be a low priority issue. @aparnasasidharan2017 I will try the fix we discussed yesterday. If it is an easy fix, I will solve it together with other issues. If not, I will not spend time on it right now.
