### ISSUE TITLE
Chronolog Testing and Testcases

### ISSUE THREAD

**Issue by aparnasasidharan2017** [grc-iit/chronolog#24]
Remove redundant tests from sub directories. Consolidate all Chronolog testcases into a single testing directory. Add test cases to top level CMakelists.txt (easily accessible). Test cases in external libs can be maintained as in. No need to add external libs to Chronolog testing infrastructure.

**Comment by ibrodkin** [comment]
the changes done under this task are merged into develop branch. closing the issue
