### ISSUE TITLE
Add libfabric to ChronoLog build files 

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#34]
Current ChronoLog buiold environment is defined in a way that libfabric is picked up by Spack as a dependency of mochi suite so ChronoLog code does build . The issue is that the default libfabric  being picked up  doesn't support any protocols other than "ofi+sockets" ; current  ChronoLog build targets do not recognize anything else as a valid protocol

we need to add explicit instructions to ChronoLog build environment files to pull the most recent stable libfabric version and rebuild it with explicit options for protocols we want to be supported in ChronoLog ( at least -tcp , -udp, -sockets )

**Comment by ibrodkin** [comment]
changes in spack.yaml are complete , testing on local machine passed , pending on Ares availability to complete testing

**Comment by fkengun** [comment]
#48

**Comment by fkengun** [comment]
Todo: update README.md to clarify protocols ChronoLog support right now
Todo: make sure MPICH works as usual with added verbs support

**Comment by fkengun** [comment]
README has been updated.
MPICH with verbs-enabled libfabric has been tested to work with both Ethernet IP and RoCE IP.
