### ISSUE TITLE
Extend Acquire/Release Visor APIs

### ISSUE THREAD

**Issue by aparnasasidharan2017** [grc-iit/chronolog#36]
When a client calls release RPC, the current implementation does not check if the client has previously acquired the chronicle. It increments/decrements the acquisition count. That could lead to a potential incorrect scenario where a client acquires a chronicle/story and another client releases it, setting the acquisition count to zero. A third client could delete the chronicle/story. 

- The AcquireChronicle and AcquireStory Maps or the ChronicleMaps and StoryMaps have to store the client ids for cross referencing acquire/release API calls.

**Comment by ibrodkin** [comment]
AcquireMaps should definitely store client ids.  A few other things you might consider while looking at this code: 
- do we keep the time limit on story acquisition and kick out the clients that linger around for too long?
- do we reject chronicle delete when the acquisition count >0 or do we kick out the other clients and allow it to proceed?
- do we need to distinguish writing vs reading clients?
- how does the client role & permissions play into the acquisition priorities ?
etc....
