### ISSUE TITLE
Keeper:  initial version of Story Recording Pipeline

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#38]
Implement initial version of Story sequencing pipeline in memory of the individual ChronoKeeper process  and  the logic of its engagement with the IngestionQueue & KeeperRecordingService. 

- IngestionQueue would split incoming stream of messages by story
- IngestionQueue should assume concurrent access by multiple ingestion threads
- Sorting/Sequencing Pipeline should assume access by multiple sequencing threads
- StoryPipeline should engage with the IngestionQueue when StoryAcquisition message  is received over KeeperVisor RPC channel
- StoryPipeline  should disengage from the IngestionQueue when StoryRelease message is received over KeeperVisor RPC channel

**Comment by fkengun** [comment]
@fkengun Prepare a use case where using the timestamp of the last event one Keeper received locally as the starting point to calculate the acceptance window cannot provide the guarantee of total ordering.

**Comment by ibrodkin** [comment]
PR with the changes : https://github.com/scs-lab/ChronoLog/pull/51

**Comment by ibrodkin** [comment]
changes are merged into develop branch
