### ISSUE TITLE
Audit and Revise Metadata maps

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#46]
We currently have a multitude of maps under  Visor Metadata Directory implementation

I believe we can consolidate a bunch of these maps into a more complex but also more concise data repository that minimize the number of lookup operations used for Visor functions and also allow for chronicle/story centered grouping of metadata and locks associated with them

**Comment by fkengun** [comment]
@fkengun Think about use cases when each of existing data structures needs to be used. If some data structures can be avoided, we can consolidate it.
Prepare slides for in-person meeting on this Thursday. List options and pros and cons of them.
Start with data flow for all APIs.
Check other systems for reference.

**Comment by akougkas** [comment]
- [] @fkengun will present Thursday March 9th a new strategy to consolidate the maps and avoid overheads from metadata operations

**Comment by fkengun** [comment]
Design document: https://docs.google.com/document/d/1ExZJG705dCBtn_i4TRHSHI9azBRN6mrbX_6FMhzfla4/edit#
Metadata table design: https://docs.google.com/spreadsheets/d/1qOfCrouyHkQ1A0tWZYuQsI-7rjFtjgEde9CSZ8j--UA/edit#gid=598142006

**Comment by fkengun** [comment]
Merged in #61
