### ISSUE TITLE
Standardize logging 

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#53]
We are using mochi library for all communication and IO . It would be logical to use mochi::logger for our logging needs

**Comment by iameneko** [comment]
Report of the work done:

[_53___Logging_Standardization_Report.pdf](https://github.com/grc-iit/ChronoLog/files/13844068/_53___Logging_Standardization_Report.pdf)

**Comment by iameneko** [comment]
Updated documentation: 
[__53_LoggingStandardizationReport_v2.pdf](https://github.com/grc-iit/ChronoLog/files/14450421/__53_LoggingStandardizationReport_v2.pdf)
