### ISSUE TITLE
Standardize ChronoLog code exception handling 

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#54]
As discussed at Jun15 meeting  all thallium generated exceptions in chronolog code need to be caught and translated into error code

we do not throw exceptions in chronolog client library but provide error return codes on client API calls instead

**Comment by fkengun** [comment]
we also need a way to exit ChronoLog services peacefully. for example, capture SIGINT to terminate.
but I am not sure if we need it for this release.

**Comment by ibrodkin** [comment]
I've aded a separate issue for basic signal handling : https://github.com/scs-lab/ChronoLog/issues/79

**Comment by ibrodkin** [comment]
completed and merged to develop
