### ISSUE TITLE
StoryLine to HDF5 Archive 

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#58]
Research HDF5 format and propose serialization/encoding layout to write our StoryPipeline into the HDF5 file format and read it back from HDF5 into StoryPipeline

StoryPipeline is the memory representation of the individual story recording that ChrronoKeeper, ChronoGrapher , and ChronoPlayer will be using.  
StoryPipeline contains the ordered map of StoryChunks, keyed by StoryChunk.startTimestamp, the individual 
Each StoryChunk is the ordered map of individual Events  within the time interval [startTimestamp, endTimestamp[    including startTimestamp, excluding endTimestamp )

The StoryChunks in the same StoryPipeline have all the same chunkGranularity (startTimestamp :endTimestamp duration) that is defined at the time of StoryAcqusition. 
The StoryChunks time periods in the pipeline do not overlap. 

Assume that the StoryPipeline represents some subset of the Story with the time range [t1 : t2]   that may or may not be the whole story.

The idea is to persist/archive the StoryPipeline from memory into HDF5 format file  and load it back from HDF5 into memory for playback given some time range.  
I assume that archiveGranualrity would be some multiple of the StoryChunk granularity depending on the size of the individual StoryChunks and the time boundaries of the individual StoryChunks will be  used as time offsets recorded in HDF5 format

Let's discuss the proposed HDF5 layout before you get to implementation

**Comment by fkengun** [comment]
Mapping design: https://docs.google.com/drawings/d/1DibH-sBQ36baxaYPWCPKgw0wIArkIkYGwyz5GQZVTv0/edit

**Comment by fkengun** [comment]
Decision is made to avoid using std::string as the payload data type and use a byte array (void *) with a size field. Will need to look into how to support variable length byte array (not string) in HDF5 data type.

**Comment by fkengun** [comment]
New mapping design using vlen data type in HDF5 without serialization: https://docs.google.com/drawings/d/1N2x9mtqL9y2m-ns5EH3mH4boPEaHiz-GzaV7nPRV2hQ/edit

**Comment by ibrodkin** [comment]
changes merged to develop
