### ISSUE TITLE
Assembled design document

### ISSUE THREAD

**Issue by fkengun** [grc-iit/chronolog#59]
Due to some historic reasons and our creative team, there is no such an assembled design document to reflect the latest design details. That is not good for the whole team, especially those who join later and miss the first year of discussion and development. 
We already have some design documents and figures hidden deeply in the shared google drive. Most of them are outdated but cannot updated to the latest version. Rewriting can be avoided to save time. 
This issue is created to address it by creating a single document to link/include the most important, if not all of them, up-to-date design details into one place. Thus, all team members can have something, either text or figure, to refer to and agree on between meetings for discussion or development. It can also save time to redraw and re-sync during the in-person meeting.
The detailed work of this issue involves:
- Updated all existing documents/figures to the latest design
- Include all updated documents/figures into one single document

**Comment by fkengun** [comment]
A unfinished first draft has been created at https://docs.google.com/document/d/1nJZUOupgLHwXc7d0-eSCccjEzeoNqAnl18HD2kIqKTs/edit#.

**Comment by ibrodkin** [comment]
we can extract material in our annual report for the design document

**Comment by ibrodkin** [comment]
we've created a wiki for ChronoLog release 1.1.    This is sufficient for the time being.
We should definitely spend some time organizing/purging our Google drive document repository going forward, but I think document repo organization is beyond the scope of this ticket. Closing
