### ISSUE TITLE
ClockSynchronization Client API 

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#8]
ChronoVisor process is is the ultimate authority on the Chrono Cluster time .

ChronoVisor client API needs functionality to expose ChronoVisor time to the client 

This API is intended to be used at the time of Visor and client initial handshake, at the time of Chronicle acquisition, and may also be forcefully triggered by the Visor in the case of client event timestamps drifting away from the Visor time beyond some configurable threshold.

**Comment by fkengun** [comment]
all my changes are in the branch [8-clocksynchronization-client-api](https://github.com/scs-lab/ChronoLog/tree/df1c03a4273e062419ad50f6dd56b13f0765489d).

**Comment by ibrodkin** [comment]
review what was done under this ticket, merge the minimum that can be used in current implementation to the develop branch, and close this ticket

**Comment by ibrodkin** [comment]
current situation is that all the ChronoLog components rely on OS timestamps and node synchronization protocol (ptp/ntp) used on HPC installation. 
I'm closing this ticket. If ChronoLog specific synchronization mechanism is reintroduced in the future new tickets would be opened.
