### ISSUE TITLE
Range query support in StoryReader

### ISSUE THREAD

**Issue by fkengun** [grc-iit/chronolog#81]
Based on the design of ChronoLog, range query will be much more widely used than full read that the current StoryReader supports.

Requirements:
- `StoryReader::readStory(chronicle_name, story_id)` returns a `std::map<start_time, LogEvent>` with all Events in the specified Story
- `StoryReader::readStoryRange(chronicle_name, story_id, start_time, end_time)` returns a `std::map<start_time, LogEvent>` with all Event within the specified time range in the specified Story

**Comment by ibrodkin** [comment]
I think the client API for story reading should return a sorted vector of events rather than a map

**Comment by ibrodkin** [comment]
merged
